// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RateAiArt.Data;

#nullable disable

namespace RateAiArt.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260719105920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RateAiArt.Data.Models.ArtModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Arts");
                });

            modelBuilder.Entity("RateAiArt.Data.Models.ArtPublisherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LeaderBoardRate")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("RateAiArt.Data.Models.ArtRateResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtId")
                        .HasColumnType("int");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<int>("Composition")
                        .HasColumnType("int");

                    b.Property<int>("Creativity")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ImprovementTips")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LightingAndColors")
                        .HasColumnType("int");

                    b.Property<int>("RenderQuality")
                        .HasColumnType("int");

                    b.Property<int>("StylisticConsistency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtId")
                        .IsUnique();

                    b.ToTable("ArtRateResults");
                });

            modelBuilder.Entity("RateAiArt.Data.Models.PublisherLeaderBoardScoreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("LeaderBoardRate")
                        .HasColumnType("double");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("PublisherLeaderBoardScores");
                });

            modelBuilder.Entity("RateAiArt.Data.Models.ArtModel", b =>
                {
                    b.HasOne("RateAiArt.Data.Models.ArtPublisherModel", "Publisher")
                        .WithMany("Arts")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("RateAiArt.Data.Models.ArtRateResultModel", b =>
                {
                    b.HasOne("RateAiArt.Data.Models.ArtModel", "Art")
                        .WithOne("ArtRateResultModel")
                        .HasForeignKey("RateAiArt.Data.Models.ArtRateResultModel", "ArtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Art");
                });

            modelBuilder.Entity("RateAiArt.Data.Models.PublisherLeaderBoardScoreModel", b =>
                {
                    b.HasOne("RateAiArt.Data.Models.ArtPublisherModel", "Publisher")
                        .WithMany("LeaderBoardScores")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("RateAiArt.Data.Models.ArtModel", b =>
                {
                    b.Navigation("ArtRateResultModel")
                        .IsRequired();
                });

            modelBuilder.Entity("RateAiArt.Data.Models.ArtPublisherModel", b =>
                {
                    b.Navigation("Arts");

                    b.Navigation("LeaderBoardScores");
                });
#pragma warning restore 612, 618
        }
    }
}
